### ISSUE TITLE
Trouble while installing in Google Colab

### ISSUE THREAD

**Issue by 1heman** [hesther/espsim#10]
Hey Hesther,

Looking at all the appreciation and its presence in various other sources, I feel at loss not being able to use it.
Can you please help me installing it in Google Colab?

Thanks in advance
-Hemant

**Comment by hesther** [comment]
I haven't used Colab in a while, but can definitely try and get back to you!

**Comment by hesther** [comment]
You can do (within Colab):

```
!pip install -q condacolab
import condacolab
condacolab.install()

!conda install -y -c rdkit -c pytorch -c psi4 -c conda-forge rdkit pytorch scikit-learn scipy joblib tqdm psi4 resp 
!pip install git+https://github.com/hesther/chemprop-atom-bond.git
!pip install git+https://github.com/hesther/espsim.git
```

I am not super proficient with Colab, so there might be better ways to do this, but this worked for me. If you reopen the notebook you will have to execute this again to install Conda and the relevant packages (takes a minute or two).

**Note:** Currently this will fail if you use` partialCharges='ml'` in GetEspSim() because I forgot to package a file correctly. Will fix that ASAP. But you can already use all other functionalities.

**Comment by 1heman** [comment]
Wow! That was pretty quick.
Thanks a ton.

**Comment by hesther** [comment]
Just pushed a new version where ML charges now also work on Colab, yay! (By the way, if Colab gives you a warning about previously imported packaged in this runtime when installing Chemprop you may safely ignore it).

**Comment by 1heman** [comment]
That's great. Thank you
