### ISSUE TITLE
Setting number of cores to use

### ISSUE THREAD

**Issue by RobinPoelmans** [hesther/espsim#26]
Hi,

I really like the ESP-Sim package, but I would like to speed up the calculations for larger datasets. I see that ESP-Sim only uses one CPU core on my machine. Is there an easy way to set the number of cores I want to use for ESP-Sim calculations?

(Sorry if this is a noob question)

Thank you in advance!

Robin

**Comment by hesther** [comment]
Hi Robin,
You can use the joblib library to parallelize over function cores. E.g. if you want to compute something over a large dataset, instead of
```
results = [f(x) for x in large_dataset]
```
you could do 
```
from joblib import Parallel,  delayed
results = Parallel(n_jobs=8, verbose=1)(delayed(f)(x) for x in large_dataset)
```
to parallelize over 8 cores (or any other number you want). You can use any function, e.g. GetEspSim, or EmbedAlignConstrainedScore, etc. You can check out the benchmarks 3 and 4 in the benchmarks folder to see examples.

**Comment by RobinPoelmans** [comment]
This is a great solution, thank you so much!

Kind regards,
Robin
